new_gui/apps/admin2/urls.py
"""URLs de admin2 """
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#local views
from apps.admin2.views import (ListAthletesView,
        DetailAthleteView, CreateAthleteView,
        UpdateAthleteView, CreateCoachView, UpdateCoachView,
        ListCoachView, delete, DetailCoachView
        )

urlpatterns = [
        path(
            route = '-AthleteList/',
            view = ListAthletesView.as_view(),
            name = "AthleteList",
            ),
        path(
            route = '-AthleteDetail/<numero_id>',
            view = DetailAthleteView.as_view(),
            name = "DetailAthlete"
            ),
        path(
            route = '-CreateAthlete/',
            view = CreateAthleteView.as_view(),
            name = "CreateAthlete",
            ),
        path(
            route = '-UpdateAthlete/<numero_id>',
            view = UpdateAthleteView.as_view(),
            name = "UpdateAthlete",
            ),
        path(
            route = '-DeleteAthlete/<athlete_id>',
            view = delete,
            name = "DeleteAthlete",
            ),
        path(
            route = '-CreateCoach/',
            view = CreateCoachView.as_view(),
            name = "CreateCoach",
            ),
        path(
            route = '-UpdateCoach/<numero_id>',
            view = UpdateCoachView.as_view(),
            name = "UpdateCoach",
            ),
        path(
            route = '-CoachList/',
            view = ListCoachView.as_view(),
            name = "CoachList",
            ),
        path(
            route = '-DetailCoach/<numero_id>',
            view = DetailCoachView.as_view(),
            name = "DetailCoach",
            ),
        ]

new_gui/apps/start_block/urls.py
"""URLs de starting block """
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#local views
from apps.start_block.views import (
        get_data, CreateSessionView, results,
        DetailSessionView, ListSessionView,
        delete
        )
from apps.admin2.views import (ListAthletesView,
        DetailAthleteView,
        )

urlpatterns = [
        path(
            route = '-home/',
            view = CreateSessionView.as_view(),
            name = "home",
            ),
        path(
            route = '-get/',
            view = get_data,
            name = "get_data",
            ),
        path(
            route = '-DeleteSession/<session_id>',
            view = delete,
            name = "DeleteSession",
            ),
        path(
            route = '-results/',
            view = results,
            name = "results",
            ),
        path(
            route = '-session/<session_id>',
            view = DetailSessionView.as_view(),
            name = "DetailSession",
            ),
        path(
            route = '-session-list',
            view = ListSessionView.as_view(),
            name = "SessionList"
            ),
        ]

new_gui/new_gui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#local views
from .views import (serial_list, home, update_view,
        )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('update/', update_view, name='UpdateView'),
    path(
        'admin2',
        include(
            ('apps.admin2.urls','admin2'),
            namespace='admin2')
        ),
    path(
        'relays',
        include(
            ('apps.relays.urls','relays'),
            namespace='relays')
        ),
    path(
        'start_block',
        include(
            ('apps.start_block.urls','start_block'),
            namespace='start_block')
        ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

new_gui/templates/start_point/list_sessions.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Liste des Sessions</h1>

	<!-- DataTales Example -->
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Liste</h6>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
						</tr>
							<th>Pic</th>
							<th>Athlete</th>
							<th>Coach</th>
							<th>Date</th>
							<th>Fichier a exporter</th>
					</thead>
					<tfoot>
						<tr>
							<th>Pic</th>
							<th>Athlete</th>
							<th>Coach</th>
							<th>Date</th>
							<th>Fichier a exporter</th>
						</tr>
					</tfoot>
					<tbody>
							{% for session in object_list %}
						<tr>
							<td>
								{% if session.athlete.photo %}
								<div>
	<a href="{% url "admin2:DetailAthlete" session.athlete.numero_id %}">
									<img width="20"	class="rounded-circle" src="/media/{{session.athlete.photo}}">
	</a>
								</div>
								{% endif %}
								<a href="{% url "start_block:DeleteSession" session.id %}">
									<i class="fas fa-trash"></i>
								</a>
							</td>
							<td>
	<a href="{% url "admin2:DetailAthlete" session.athlete.numero_id %}">
								{{session.athlete}}
	</a>
							</td>
							<td>
								<a href="{% url "admin2:DetailCoach" session.coach.numero_id %}">
									{{session.coach}}
								</a>
							</td>
							<th>
								<a href="{% url "start_block:DetailSession" session.id %}">
									{{session.created}}
								</a>
							</th>
							<td>
								<a href="static/data/{{session.data}}.csv">
									fichier.csv
								</a>
							</td>
						</tr>
							{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{% endblock %}
			{% block Scripts %}
    <!-- Page level plugins -->
    <script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static "js/demo/datatables-demo.js" %}"></script>

	{% endblock %}

new_gui/templates/start_point/results.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
		<!-- Begin Page Content -->
		<div class="container-fluid">

				<!-- Page Heading -->
				<h1 class="h3 mb-2 text-gray-800">Charts</h1>

				<!-- Content Row -->
				<div class="row">


							<!-- Collapsable Card Gauche -->
							<div class="card shadow mb-4">
									<!-- Card Header - Accordion -->
									<a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
											role="button" aria-expanded="true" aria-controls="collapseCardExample">
											<h6 class="m-0 font-weight-bold text-primary">Graph</h6>
									</a>
									<!-- Card Content - Collapse -->
									<div class="collapse show" id="collapseCardExample">
											<div class="card-body">
												<img src="{% static graph_gauche %}">
												<br>
												Max force gauche = {{max_force_gauche}}<br>
												Max force droit = {{max_force_droit}}
											</div>
									</div>
							</div>

				</div>

		</div>
		<!-- /.container-fluid -->

{% endblock %}