new_gui/apps/admin2/urls.py
"""URLs de admin2 """
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#local views
from apps.admin2.views import (ListAthletesView,
        DetailAthleteView, CreateAthleteView,
        UpdateAthleteView, CreateCoachView, UpdateCoachView,
        ListCoachView, delete, DetailCoachView
        )

urlpatterns = [
        path(
            route = '-AthleteList/',
            view = ListAthletesView.as_view(),
            name = "AthleteList",
            ),
        path(
            route = '-AthleteDetail/<numero_id>',
            view = DetailAthleteView.as_view(),
            name = "DetailAthlete"
            ),
        path(
            route = '-CreateAthlete/',
            view = CreateAthleteView.as_view(),
            name = "CreateAthlete",
            ),
        path(
            route = '-UpdateAthlete/<numero_id>',
            view = UpdateAthleteView.as_view(),
            name = "UpdateAthlete",
            ),
        path(
            route = '-DeleteAthlete/<athlete_id>',
            view = delete,
            name = "DeleteAthlete",
            ),
        path(
            route = '-CreateCoach/',
            view = CreateCoachView.as_view(),
            name = "CreateCoach",
            ),
        path(
            route = '-UpdateCoach/<numero_id>',
            view = UpdateCoachView.as_view(),
            name = "UpdateCoach",
            ),
        path(
            route = '-CoachList/',
            view = ListCoachView.as_view(),
            name = "CoachList",
            ),
        path(
            route = '-DetailCoach/<numero_id>',
            view = DetailCoachView.as_view(),
            name = "DetailCoach",
            ),
        ]

new_gui/apps/start_block/urls.py
"""URLs de starting block """
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#local views
from apps.start_block.views import (
        get_data, CreateSessionView, results,
        DetailSessionView, ListSessionView,
        delete
        )
from apps.admin2.views import (ListAthletesView,
        DetailAthleteView,
        )

urlpatterns = [
        path(
            route = '-home/',
            view = CreateSessionView.as_view(),
            name = "home",
            ),
        path(
            route = '-get/',
            view = get_data,
            name = "get_data",
            ),
        path(
            route = '-DeleteSession/<session_id>',
            view = delete,
            name = "DeleteSession",
            ),
        path(
            route = '-results/',
            view = results,
            name = "results",
            ),
        path(
            route = '-session/<session_id>',
            view = DetailSessionView.as_view(),
            name = "DetailSession",
            ),
        path(
            route = '-session-list',
            view = ListSessionView.as_view(),
            name = "SessionList"
            ),
        ]

new_gui/new_gui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#local views
from .views import (serial_list, home, update_view,
        )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('update/', update_view, name='UpdateView'),
    path(
        'admin2',
        include(
            ('apps.admin2.urls','admin2'),
            namespace='admin2')
        ),
    path(
        'relays',
        include(
            ('apps.relays.urls','relays'),
            namespace='relays')
        ),
    path(
        'start_block',
        include(
            ('apps.start_block.urls','start_block'),
            namespace='start_block')
        ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

new_gui/apps/start_block/models.py
from django.db import models
from apps.admin2.models import Athletes,Coach

def get_coach():
    return Coach.objects.get_or_create(id=1)


class Session(models.Model):
    athlete =  models.ForeignKey(
            'admin2.Athletes',
            verbose_name='Athlete',
            on_delete = models.CASCADE,
            )
    coach =  models.ForeignKey(
            'admin2.Coach',
            verbose_name='Coach',
            on_delete = models.CASCADE,
            )
    data = models.FileField(
            upload_to='static/data/',
            )
    max_force_left = models.IntegerField(
            default=10,
            blank=True,
            )
    max_force_right = models.IntegerField(
            default=10,
            blank=True,
            )
    enabled = models.BooleanField(
            default = True
            )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return F"{self.athlete} => {self.created} par {self.coach}"

new_gui/apps/start_block/views.py
#python
import os
import socket
import time
import csv
from pathlib import Path

#django modules
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic import DetailView, FormView, ListView

#models
from apps.start_block.models import Session
from apps.admin2.models import Athletes, Coach

#local functions
from .math_functions import graph_data, save_csv_data

class DetailSessionView(DetailView):
    template_name = 'start_point/results.html'
    model = Session
    pk_url_kwarg = 'session_id'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session_id = context['object'].id
        session_data = Session.objects.get(pk = session_id)
        file_name = session_data.data
        context["graph_gauche"] = F"data/{file_name}_left.png"
        context["graph_droit"] = F"data/{file_name}_right.png"
        context["max_force_gauche"] = session_data.max_force_left
        context['max_force_droit'] = session_data.max_force_right
        return context

def delete(request, session_id):
    data = Session.objects.filter(id = session_id)
    data.update(
            enabled = False,
            )
    return redirect("start_block:SessionList")

class CreateSessionView(CreateView):
    model = Session
    fields = [
            'athlete',
            'coach',
            ]
    template_name = "start_point_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['file_name'] = generate_file_name()
        return context

def generate_file_name():
    year = time.localtime()[0]
    month =  time.localtime()[1]
    day =  time.localtime()[2]
    hour =  time.localtime()[3]
    mins =  time.localtime()[4]
    sec =  time.localtime()[5]
    name = F"{year}_{month}_{day}_{hour}_{mins}_{sec}"
    return name

def results(request):
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    template_name = 'start_point/results.html'

    #get info from web page
    coach_id = request.POST["coach"]
    coach_name = Coach.objects.get(
            id = coach_id
            ).nom
    athlete_id = request.POST["athlete"]
    athlete_name = Athletes.objects.get(
            id = athlete_id
            ).nom
    file_name = request.POST["data"]
    file_name = F"{coach_name}__{athlete_name}_{file_name}"
    save_csv_data(file_name)

    print("graficando")
    max_force_gauche, max_force_droit = graph_data(file_name)

    #context data
    data = {
            "graph_gauche": F"data/{file_name}_left.png",
            "max_force_gauche": max_force_gauche,
            'max_force_droit': max_force_droit,
            }

    #saving model
    new_data = Session(
            data = file_name,
            athlete = Athletes.objects.get(id=request.POST['athlete']),
            coach = Coach.objects.get(id=request.POST['coach']),
            max_force_left = max_force_gauche,
            max_force_right = max_force_droit,
            )
    new_data.save()

    return render(
            request,
            template_name,
            context = data
            )

def get_data(request):
    name = request.POST["data"]
    file = open(name, "a")

    #if(request.method == "GET"):
    #    return redirect("start_block:home")

    s_point = socket.socket()
    port = 50
    host = "10.20.1.56"
    print(F"Connecting to {host} in port {port}")
    s_point.connect((host, port))
    try:
        message = b"1"
        s_point.send(message)

        data = b""
        number = 0
        llega = b""
        print(F'Receiving data in {name}')
        while (not data == b"!"):
            data = s_point.recv(1)
            #print(data)
            llega += data
            if (data == b"\n"):
                number += 1
                #print(F"{number} = {str(llega)}")
                file.write(F"{llega.decode('ascii')}")
                llega = b""

    except Exception as E:
        print("Error: ")
        print(E)

    file.close()
    s_point.close()
    new_data = Session()
    new_data.athlete = Athletes.objects.get(id=request.POST['athlete'])
    new_data.data = request.POST['data']
    new_data.save()

    return redirect("start_block:home")

class ListSessionView(ListView):
    model = Session
    template_name = 'start_point/list_sessions.html'

    def get_queryset(self):
        return Session.objects.filter(
                athlete__enabled = True,
                ).exclude(
                enabled = False,
                )

    def get_ordering(self):
        ordering = self.request.GET.get('ordering', 'created')
        # validate ordering here
        return ordering

new_gui/templates/coach_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Liste des Coachs</h1>

	<!-- DataTales Example -->
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Liste</h6>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
						</tr>
							<th>Pic</th>
							<th>Numero ID</th>
							<th>Nom</th>
							<th>Prenom</th>
							<th>Categorie Entraine</th>
							<th>Date de Naissance</th>
							<th>Membre depuis</th>
					</thead>
					<tfoot>
						<tr>
							<th>Pic</th>
							<th>Numero ID</th>
							<th>Nom</th>
							<th>Prenom</th>
							<th>Categorie Entraine</th>
							<th>Date de Naissance</th>
							<th>Membre depuis</th>
						</tr>
					</tfoot>
					<tbody>
							{% for coach in object_list %}
						<tr>
							<td>
								{% if coach.photo %}
								<div>
									<img width="20"	class="rounded-circle" src="/media/{{coach.photo}}">
								</div>
								{% endif %}
							</td>
								<td>
								<a href="{% url "admin2:DetailCoach" coach.numero_id %}">
										{{coach.numero_id}}
								</a>
								<br>
								<a href="{% url "admin2:UpdateCoach" coach.numero_id %}">
										Modifier
								</a>
								</td>
								<td>{{coach.nom}}</td>
								<td>{{coach.prenom}}</td>
								<td>{{coach.categorie}}</td>
								<td>{{coach.date_naissance}}</td>
								<td>{{coach.created}}</td>
						</tr>
							{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{% endblock %}
{% block Scripts %}
<!-- Page level plugins -->
<script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

<!-- Page level custom scripts -->
<script src="{% static "js/demo/datatables-demo.js" %}"></script>

{% endblock %}

new_gui/templates/create_athlete.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user">
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                            placeholder="First Name">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" id="exampleLastName"
                                            placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email Address">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a>
                                <hr>
                                <a href="index.html" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Register with Google
                                </a>
                                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                                </a>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="login.html">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

new_gui/templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

new_gui/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
<div class="container-fluid">

	<div class="card o-hidden border-0 shadow-lg my-5">
			<div class="card-body p-0">
					<!-- Nested Row within Card Body -->
				<div class="row">
						<div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
						<div class="col-lg-7">
								<div class="p-5">
										<div class="text-center">
											<h1 class="h4 text-gray-900 mb-4">{{ title }}</h1>
											<img
											src="{% static "img/balma_logo.png" %}"
											width=120
											>
											<br>
											{% if starting_block.connected %}
											Starting Block : Connected
											<br>
											<i class="{{starting_block.icon}}"></i>
											{{ starting_block.charge}}%
											{% endif %}
											<br>
											{% if serial_ports %}
											Temoins connectes <br>
											{% for port in serial_ports %}
											{{ port }}
											<br>
											{% endfor %}
											{% endif %}
										</div>
								</div>
						</div>
				</div>
			</div>
	</div>

{% endblock %}

new_gui/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Graphs</h1>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Generate report</a>
                                <!-- Button to create graphics -->
                    </div>

                    <!-- Content Row -->
                    <div class="row">


                    <div class="row">

                        <!-- Area Chart -->
                        <div class="col-xl-8 col-lg-7">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div
                                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">Speed Plot</h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                            aria-labelledby="dropdownMenuLink">
                                            <div class="dropdown-header">Dropdown Header:</div>
                                            <a class="dropdown-item" href="#">Action</a>
                                            <a class="dropdown-item" href="#">Another action</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Something else here</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
										<img src="{% static 'img/graph.png' %}" >
										{% for vel in speed %}
											<p> vel = {{ vel }}</p><br>
										{% endfor %}
										<p> Mean speed = {{mean_speed}} </p>

                                </div>
                            </div>
                        </div>
                        <!-- Area Chart -->
                        <div class="col-xl-8 col-lg-7">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div
                                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">Relais bien faits</h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                            aria-labelledby="dropdownMenuLink">
                                            <div class="dropdown-header">Dropdown Header:</div>
                                            <a class="dropdown-item" href="#">Action</a>
                                            <a class="dropdown-item" href="#">Another action</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Something else here</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                  <img src="{% static 'img/graph2.png' %}" >

                                </div>
                            </div>
                        </div>

                    </div>


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; UT3 Paul Sabatier</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
            {% endblock %}

new_gui/templates/serial_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Select Port:</h1>
                        <form method="POST" action="{% url "report_page" %}">
                          {% csrf_token %}
                          <select name="port" id="cars">
                            {% for port in serial_ports_list %}
                            <option value="{{port}}">{{port}}</option>
                            {% endfor %}
                          </select>
                          <br><br>
						  Ecrivez la distance jusqua la premier zone de transmission
						  <input name="distance1" type="number">
                          <br><br>
						  Ecrivez la distance jusqua la deuxieme zone de transmission
						  <input name="distance2" type="number">
                          <br><br>
						  Ecrivez la distance jusqua la troisieme zone de transmission
						  <input name="distance3" type="number">
                          <br><br>
						  Ecrivez la distance jusqua la quatrieme zone de transmission
						  <input name="distance4" type="number">
                          <br><br>
						  Ecrivez la distance jusqua la cinquieme zone de transmission
						  <input name="distance5" type="number">
                          <br><br>
						  Ecrivez la distance de la zone de transmission
						  <input name="distancet" type="number">
                          <br><br>

                          <input type="submit" value="Submit">
                        </form>
                    </div>
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; UT3 Paul Sabatier</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        <!-- End of Content Wrapper -->
            {% endblock %}

new_gui/templates/start_point_home.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
	<!-- Begin Page Content -->
<div class="container-fluid">
	<!-- Page Heading -->
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
		<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">Create New Session</h6>
		</div>
		<div class="card-body">
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<form method="POST" action="{% url "start_block:results" %}">
			{% csrf_token %}
			{{form}}
			<br><br>
			<input name="data" type="text" value="{{file_name}}" hidden>
			<br><br>
			<input type="submit" value="Submit">
		</form>
	</div>
		</div>
</div>
<!-- End of Main Content -->
<!-- End of Content Wrapper -->
{% endblock %}