new_gui/apps/admin2/urls.py
"""URLs de admin2 """
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#local views
from apps.admin2.views import (ListAthletesView,
        DetailAthleteView, CreateAthleteView,
        UpdateAthleteView, CreateCoachView, UpdateCoachView,
        ListCoachView, delete, DetailCoachView
        )

urlpatterns = [
        path(
            route = '-AthleteList/',
            view = ListAthletesView.as_view(),
            name = "AthleteList",
            ),
        path(
            route = '-AthleteDetail/<numero_id>',
            view = DetailAthleteView.as_view(),
            name = "DetailAthlete"
            ),
        path(
            route = '-CreateAthlete/',
            view = CreateAthleteView.as_view(),
            name = "CreateAthlete",
            ),
        path(
            route = '-UpdateAthlete/<numero_id>',
            view = UpdateAthleteView.as_view(),
            name = "UpdateAthlete",
            ),
        path(
            route = '-DeleteAthlete/<athlete_id>',
            view = delete,
            name = "DeleteAthlete",
            ),
        path(
            route = '-CreateCoach/',
            view = CreateCoachView.as_view(),
            name = "CreateCoach",
            ),
        path(
            route = '-UpdateCoach/<numero_id>',
            view = UpdateCoachView.as_view(),
            name = "UpdateCoach",
            ),
        path(
            route = '-CoachList/',
            view = ListCoachView.as_view(),
            name = "CoachList",
            ),
        path(
            route = '-DetailCoach/<numero_id>',
            view = DetailCoachView.as_view(),
            name = "DetailCoach",
            ),
        ]

new_gui/apps/start_block/urls.py
"""URLs de starting block """
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#local views
from apps.start_block.views import (
        get_data, CreateSessionView, results,
        DetailSessionView, ListSessionView,
        delete
        )
from apps.admin2.views import (ListAthletesView,
        DetailAthleteView,
        )

urlpatterns = [
        path(
            route = '-home/',
            view = CreateSessionView.as_view(),
            name = "home",
            ),
        path(
            route = '-get/',
            view = get_data,
            name = "get_data",
            ),
        path(
            route = '-DeleteSession/<session_id>',
            view = delete,
            name = "DeleteSession",
            ),
        path(
            route = '-results/',
            view = results,
            name = "results",
            ),
        path(
            route = '-session/<session_id>',
            view = DetailSessionView.as_view(),
            name = "DetailSession",
            ),
        path(
            route = '-session-list',
            view = ListSessionView.as_view(),
            name = "SessionList"
            ),
        ]

new_gui/new_gui/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#local views
from .views import (serial_list, home, update_view,
        )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home, name='home'),
    path('update/', update_view, name='UpdateView'),
    path(
        'admin2',
        include(
            ('apps.admin2.urls','admin2'),
            namespace='admin2')
        ),
    path(
        'relays',
        include(
            ('apps.relays.urls','relays'),
            namespace='relays')
        ),
    path(
        'start_block',
        include(
            ('apps.start_block.urls','start_block'),
            namespace='start_block')
        ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

new_gui/apps/admin2/models.py
from django.db import models

class Athletes(models.Model):
    numero_id = models.IntegerField()
    nom = models.CharField(max_length=20)
    prenom = models.CharField(max_length=30)
    date_naissance = models.DateField()
    photo = models.ImageField(
            upload_to = 'img/',
            verbose_name="Photo de Profil (pas necessaire)",
            blank=True,
            )
    categorys = [
            ("VE", "Masters"),
            ("SE", "Seniors"),
            ("ES", "Espoirs"),
            ("JU", "Junior"),
            ("CA", "Cadets"),
            ("MI", "Minimes"),
            ("BE", "Benjamines"),
            ]
    categorie = models.CharField(
            default = "MI",
            max_length = 2,
            choices = categorys,
            )
    enabled = models.BooleanField(
            default = True
            )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)



    def __str__(self):
        return F"{self.nom}"

class Coach(models.Model):
    numero_id = models.IntegerField()
    nom = models.CharField(max_length=20)
    prenom = models.CharField(max_length=30)
    date_naissance = models.DateField()
    photo = models.ImageField(
            upload_to = 'img/',
            verbose_name="Photo de Profil (pas necessaire)",
            blank=True,
            )
    categorys = [
            ("VE", "Masters"),
            ("SE", "Seniors"),
            ("ES", "Espoirs"),
            ("JU", "Junior"),
            ("CA", "Cadets"),
            ("MI", "Minimes"),
            ("BE", "Benjamines"),
            ]
    categorie = models.CharField(
            verbose_name = "Categroie Entraine",
            default = "MI",
            max_length = 2,
            choices = categorys,
            )
    enabled = models.BooleanField(
            default = True
            )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return F"{self.nom}"

new_gui/apps/admin2/forms.py
from django import forms
from .models import Athletes, Coach

class DateInput(forms.DateInput):
    input_type = 'date'

class NumberInput(forms.NumberInput):
    input_type = 'number'

class RegisterForm(forms.ModelForm):
    class Meta:
        model = Athletes
        fields = {
                'numero_id',
                'nom',
                'prenom',
                'date_naissance',
                'photo',
                'categorie',
                }
        widgets = {
                'numero_id': NumberInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Numero ID'
                        }
                    ),
                'nom': forms.TextInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Nom'
                        }
                    ),
                'prenom': forms.TextInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Prenom'
                        }
                    ),
                'date_naissance': DateInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Numero ID'
                        }
                    ),
                'photo': forms.FileInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Numero ID'
                        }
                    ),
                'categorie': forms.Select(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Categorie'
                        }
                    ),
                }
        def save(self):
            data = self.cleaned_data
            new_data = Athletes(**data)
            new_data.save()


class CoachRegisterForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = {
                'numero_id',
                'nom',
                'prenom',
                'date_naissance',
                'photo',
                'categorie',
                }
        widgets = {
                'numero_id': NumberInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Numero ID'
                        }
                    ),
                'nom': forms.TextInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Nom'
                        }
                    ),
                'prenom': forms.TextInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Prenom'
                        }
                    ),
                'date_naissance': DateInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Numero ID'
                        }
                    ),
                'photo': forms.FileInput(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Numero ID'
                        }
                    ),
                'categorie': forms.Select(
                    attrs={
                        'class': 'form-control form-control-user',
                        'placeholder': 'Categorie Entraine'
                        }
                    ),
                }

        def save(self):
            data = self.cleaned_data
            new_data = Coach(**data)
            new_data.save()

new_gui/apps/admin2/views.py
#django modules
from django.shortcuts import render, redirect
from django.views.generic import (ListView, UpdateView,
        DetailView, FormView
        )
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.db.models import Q

#local modules
from apps.admin2.models import Athletes, Coach
from apps.start_block.models import Session
from apps.admin2.forms import RegisterForm, CoachRegisterForm

# ------ Athlete Views ------
class ListAthletesView(ListView):
    model = Athletes
    template_name = 'athlete_list.html'

    def get_queryset(self):
        #this function excludes disabled data
        return Athletes.objects.exclude(enabled=False)

class DetailAthleteView(DetailView):
    template_name = 'athlete-detail.html'
    slug_field = "numero_id"
    slug_url_kwarg = "numero_id"
    queryset = Athletes.objects.all().exclude(
            enabled = False
            )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        athlete_id = context['object'].id
        context['sessions'] = Session.objects.filter(
                athlete = athlete_id
                ).exclude(
                enabled = False
                )
        return context

class CreateAthleteView(FormView):
    success_url = reverse_lazy('admin2:AthleteList')
    form_class = RegisterForm
    template_name = 'admin2/create_athlete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Creer un compte"
        return context

    def form_valid(self, form):
        form.save()
        return super(CreateAthleteView, self).form_valid(form)

class UpdateAthleteView(UpdateView):
    template_name = 'admin2/create_athlete.html'
    model = Athletes
    slug_field = 'numero_id'
    slug_url_kwarg = 'numero_id'

    fields = [
            'numero_id',
            'nom',
            'prenom',
            'date_naissance',
            'photo',
            'categorie',
            ]
    success_url = reverse_lazy('admin2:AthleteList')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Modifier les donnes"
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

def delete(request, athlete_id):
    data = Athletes.objects.filter(id = athlete_id)
    data.update(
            enabled = False,
            )
    return redirect("admin2:AthleteList")

# ------ Coach Views ------

class CreateCoachView(FormView):
    success_url = reverse_lazy('admin2:CoachList')
    form_class = CoachRegisterForm
    template_name = 'admin2/create_athlete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Creer un compte de Coach"
        return context

    def form_valid(self, form):
        form.save()
        return super(CreateCoachView, self).form_valid(form)

class UpdateCoachView(UpdateView):
    template_name = 'admin2/create_coach.html'
    model = Coach
    slug_field = 'numero_id'
    slug_url_kwarg = 'numero_id'

    fields = [
            'numero_id',
            'nom',
            'prenom',
            'date_naissance',
            'photo',
            'categorie',
            ]
    success_url = reverse_lazy('admin2:CoachList')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Modifier les donnes du Coach"
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class ListCoachView(ListView):
    #print("coach list")
    model = Coach
    template_name = 'coach_list.html'

class DetailCoachView(DetailView):
    template_name = 'admin2/coach_detail.html'
    slug_field = "numero_id"
    slug_url_kwarg = "numero_id"

    queryset = Coach.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        coach_id = context['object'].id
        context['sessions'] = Session.objects.filter(
                coach = coach_id,
                ).exclude(
                Q(enabled = False)|
                Q(athlete__enabled = False)
                )
        return context

new_gui/templates/admin2/coach_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
<!-- Begin Page Content -->
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">{{object.nom}} {{object.prenom}}</h1>
	<a href="{% url "admin2:UpdateCoach" object.numero_id %}">
		Modifier
	</a>
	{% if object.photo %}
	<div>
		<img width="200"	class="rounded-circle" src="/media/{{object.photo}}">
	</div>
	{% endif %}
	<!-- DataTales Example -->
	<div class="card shadow mb-4">
		<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary">Sessions</h6>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<h2>Categorie entraine = {{object.categorie}}</h2>
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>Pic</th>
							<th>Athlete</th>
							<th>Categorie</th>
							<th>Date</th>
							<th>Max Force Gauche</th>
							<th>Max Force Droite</th>
							<th>Fichier</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Pic</th>
							<th>Athlete</th>
							<th>Categorie</th>
							<th>Date</th>
							<th>Max Force Gauche</th>
							<th>Max Force Droite</th>
							<th>Fichier</th>
						</tr>
					</tfoot>
					<tbody>
							{% for session in sessions %}
						<tr>
							<td>
								{% if session.athlete.photo %}
								<div>
								<a href="{% url "admin2:DetailAthlete" session.athlete.numero_id %}">
									<img width="20"	class="rounded-circle" src="/media/{{session.athlete.photo}}">
								</a>
								</div>
								{% endif %}
								<a href="{% url "start_block:DeleteSession" session.id %}">
									<i class="fas fa-trash"></i>
								</a>
							</td>
							<th>
								<a href="{% url "admin2:DetailAthlete" session.athlete.numero_id %}">
								{{session.athlete}}
								</a>
							</th>
							<th>{{session.athlete.categorie}}</th>
							<th><a href="{% url "start_block:DetailSession" session.id %}">{{session.created}} </a></th>
								<th>{{session.max_force_left}}</th>
								<th>{{session.max_force_right}}</th>
								<th><a href="static/data/{{session.data}}.csv">fichier.csv</a></th>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{% endblock %}
{% block Scripts %}
<!-- Page level plugins -->
<script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

<!-- Page level custom scripts -->
<script src="{% static "js/demo/datatables-demo.js" %}"></script>

{% endblock %}

new_gui/templates/admin2/create_athlete.html
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
<div class="container-fluid">

	<div class="card o-hidden border-0 shadow-lg my-5">
			<div class="card-body p-0">
					<!-- Nested Row within Card Body -->
				<div class="row">
						<div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
						<div class="col-lg-7">
								<div class="p-5">
										<div class="text-center">
											<h1 class="h4 text-gray-900 mb-4">{{ title }}</h1>
										</div>
										<form method="POST" enctype="multipart/form-data" class="user">
											{% csrf_token %}
												<div class="form-group row">
													{{ form.as_p }}
												</div>
												<input type="submit" value="Send" class="btn btn-primary btn-user btn-block">
										</form>
								</div>
						</div>
				</div>
			</div>
	</div>

</div>
{% endblock %}

new_gui/templates/admin2/create_coach.html
{% extends "base.html" %}
{% load static %}
{% block MainContent %}
<div class="container-fluid">

	<div class="card o-hidden border-0 shadow-lg my-5">
			<div class="card-body p-0">
					<!-- Nested Row within Card Body -->
				<div class="row">
						<div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
						<div class="col-lg-7">
								<div class="p-5">
										<div class="text-center">
											<h1 class="h4 text-gray-900 mb-4">{{ title }}</h1>
										</div>
										<form method="POST" enctype="multipart/form-data" class="user">
											{% csrf_token %}
												<div class="form-group row">
													{{ form.as_p }}
												</div>
												<input type="submit" value="Send" class="btn btn-primary btn-user btn-block">
										</form>
								</div>
						</div>
				</div>
			</div>
	</div>

</div>
{% endblock %}